name: static analysis for shell scripts using shellcheck and shfmt
on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - "**/LICENSE"
      - "**/README.md"
      - "**/README.zh-Hans-CN.md"
  pull_request:
    branches:
      - master
      - develop
jobs:
  sh-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run the sh-checker
        uses: luizm/action-sh-checker@v0.1.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          sh_checker_comment: true
          sh_checker_exclude: "LICENSE README.md README.zh-Hans-CN.md"
  filed-test:
    runs-on: ubuntu-latest
    container: 
      image: centos:centos7.0.1406
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: What OS is running
        run: uname -a
      - name: Run the filed-test
        run: |
          sudo bash install-release.sh
